name: build-docfx
description: "Build DocFX"

inputs:
  docfx-file-path:
    description: "docfx.json file path"
    required: false
    default: ""
  docfx-output-path:
    description: "Specify output folder"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build DocFX
      run: |
        parameters=""
        if [ -z ${{ inputs.docfx-file-path }}]; then
          echo "No file specified, using default."
        else
          parameters="${{ inputs.docfx-file-path }}"
        fi
        if [ -z ${{ inputs.docfx-output-path }}]; then
          echo "No output folder specified, using default."
        else
          parameters="$parameters -o:${{ inputs.docfx-output-path }}"
        fi
        docfx $parameters
      shell: bash

branding:
  icon: code
  color: green